openapi: 3.1.0
info:
  title: Palupi POS Backend API
  version: 1.0.0
  description: Backend contract for Category resource (ULID ids, soft delete).
servers:
  - url: http://localhost:8080/api/v1
    description: Dev

tags:
  - name: categories

paths:
  /categories:
    get:
      tags:
        - categories
      summary: List categories
      parameters:
        - $ref: '#/components/parameters/Q'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Offset'
        - $ref: '#/components/parameters/IncludeInactive'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryList'
    post:
      tags:
        - categories
      summary: Create category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryCreate'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: Validation error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '409':
          description: Duplicate name
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

  /categories/{id}:
    parameters:
      - $ref: '#/components/parameters/CategoryId'
    get:
      tags:
        - categories
      summary: Get category detail
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
    put:
      tags:
        - categories
      summary: Update category (replace)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryUpdate'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: Validation error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '409':
          description: Duplicate name
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
    patch:
      tags:
        - categories
      summary: Update category (partial)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                name:
                  type: string
                  maxLength: 100
                is_active:
                  type: boolean
              minProperties: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: Validation error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '409':
          description: Duplicate name
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
    delete:
      tags:
        - categories
      summary: Soft-delete category
      responses:
        '204':
          description: No Content
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

components:
  parameters:
    CategoryId:
      name: id
      in: path
      required: true
      description: ULID string
      schema:
        type: string
        minLength: 1
        maxLength: 26
    Q:
      name: q
      in: query
      description: Case-insensitive name search
      schema:
        type: string
        maxLength: 100
    Limit:
      name: limit
      in: query
      description: "Page size (1..100). Default: 20"
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
    Offset:
      name: offset
      in: query
      description: "Offset for pagination. Default: 0"
      schema:
        type: integer
        minimum: 0
        default: 0
    IncludeInactive:
      name: include_inactive
      in: query
      description: "Include inactive items when true. Default: false"
      schema:
        type: boolean
        default: false

  schemas:
    Category:
      type: object
      additionalProperties: false
      required:
        - id
        - name
        - is_active
        - created_at
        - updated_at
      properties:
        id:
          type: string
          description: ULID string
        name:
          type: string
          maxLength: 100
        is_active:
          type: boolean
          default: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
          nullable: true

    CategoryCreate:
      type: object
      additionalProperties: false
      required:
        - name
      properties:
        name:
          type: string
          maxLength: 100
          description: Unique among non-deleted rows (case-insensitive)
        is_active:
          type: boolean
          default: true

    CategoryUpdate:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
          maxLength: 100
        is_active:
          type: boolean

    CategoryList:
      type: object
      additionalProperties: false
      required:
        - data
        - limit
        - offset
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Category'
        limit:
          type: integer
          minimum: 1
          maximum: 100
          default: 20
        offset:
          type: integer
          minimum: 0
          default: 0

    Problem:
      type: object
      additionalProperties: true
      description: RFC 9457 problem details
      required:
        - title
        - status
      properties:
        type:
          type: string
          format: uri
          nullable: true
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
