### GET request to example server
GET http://localhost:8080/api/v1/categories/list

###
GET http://localhost:8080/api/v1/categories/5

###
POST http://localhost:8080/api/v1/categories/add
Content-Type: application/json

{
  "name": "Bebek aaa"
}

###
PUT http://localhost:8080/api/v1/categories/update/4
Content-Type: application/json
Accept: application/json

{
  "name": "Category Baru"
}

###
DELETE http://localhost:8080/api/v1/categories/delete/5
