### GET request to example server
GET http://localhost:8080/api/v1/categories

###
GET http://localhost:8080/api/v1/categories/4

###
POST http://localhost:8080/api/v1/categories
Content-Type: application/json

{
  "name": "ini percobaan"
}

###
PUT http://localhost:8080/api/v1/categories/6
Content-Type: application/json
Accept: application/json

{
  "name": "ini edit"
}

###
DELETE http://localhost:8080/api/v1/categories/delete/5
